language: java
key : DISPLAY
  value:0:0

before_install:
  - mvn install -DskipTests=false -Dmaven.javadoc.skip=false -B -V
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
script:
  - mvn test -Dcucumber.filter.tags=@reg
#script:
# - mvn test -Dbase.url=https://www.crowncommercial.gov.uk/ -Dcucumber.filter.tags=@axe

#cron:
#  - branch: main
#      interval: daily
#      options: not if last 1h
